# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: aQute
email: info@aQute.biz
description: > # this means to ignore newlines until "baseurl:"
  aQute is specialized in providing pragmatic expertise, services, 
  and products related to the Internet of Things with a special focus on OSGi. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aQute.biz" # the base hostname & protocol for your site
twitter_username: pkriens
github_username:  pkriens

# Build settings
markdown: kramdown
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'
  - 'run.sh'
  - '.travis.yml'
  - '/vendor'
